kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-keda-lab
networking:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
            enable-admission-plugins: NodeRestriction
      - |
        kind: KubeletConfiguration
        evictionHard:
          nodefs.available: "5%"
          imagefs.available: "5%"
          memory.available: "100Mi"
