apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-workload
  namespace: prometheus
  labels:
    app: prometheus-workload
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - lab
  selector:
    matchLabels:
      app: prometheus-workload
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
