apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cpu-scaling
  namespace: lab
  labels:
    app: cpu-workload
spec:
  scaleTargetRef:
    name: cpu-workload
  minReplicaCount: 1
  maxReplicaCount: 10
  cooldownPeriod: 300
  pollingInterval: 15
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "50"
